server:
  port: ${SERVER_PORT:8080}

spring:
  main:
    banner-mode: off
  application:
    name: kpi-with-web-flux-1.0.0
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:${DB_DRIVER:mariadb}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:kpi}
    user: ${DB_USER:root}
    password: ${DB_PASS:password}
    schemas: ${DB_SCHEMA:kpi}
  datasource:
    url: jdbc:${DB_DRIVER:mariadb}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:kpi}
    username: ${DB_USER:root}
    password: ${DB_PASS:password}
#    driver-class-name: ${DB_DRIVER_CLASSNAME:com.mysql.cj.jdbc.Driver}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql: ERROR

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html