server:
  port: ${SERVER_PORT:8080}

spring:
  main:
    banner-mode: off
  application:
    name: kpi-with-web-flux-1.0.0
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:${DB_DRIVER:mariadb}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:kpi}
    user: ${DB_USER:root}
    password: ${DB_PASS:password}
    schemas: ${DB_SCHEMA:kpi}
  r2dbc:
    url: r2dbc:${DB_DRIVER:mariadb}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHEMA:kpi}
    username: ${DB_USER:root}
    password: ${DB_PASS:password}
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
