INSERT INTO `m_level` (`level`, `status`, `created_by`) VALUES
	('President', 'Disabled', 'system'),
	('Direktur Utama / CEO', 'Enabled', 'system'),
	('Direktur Umum / Teknik', 'Enabled', 'system'),
	('Vice President', 'Disabled', 'system'),
	('Senior Manager', 'Disabled', 'system'),
	('Manager', 'Enabled', 'system'),
	('Assistant Manager', 'Disabled', 'system'),
	('Expert', 'Disabled', 'system'),
	('Supervisor', 'Enabled', 'system'),
	('Specialist', 'Disabled', 'system'),
	('Junior Specialist', 'Disabled', 'system'),
	('Staff', 'Enabled', 'system'),
	('Non Staff', 'Enabled', 'system');

INSERT INTO `m_profesi` (`level_id`, `name`, `status`,`created_by`) VALUES
	(6, 'Manajer Perencanaan & Pengembangan ', 'Enabled', 'system'),
	(6, 'Manajer Produksi & Distribusi 1', 'Enabled', 'system'),
	(6, 'Manajer Pengendalian Teknik', 'Enabled', 'system'),
	(6, 'Manajer Keuangan', 'Enabled', 'system'),
	(6, 'Manajer Kesekretariatan', 'Enabled', 'system'),
	(6, 'Manajer Sumber Daya Manusia & TI', 'system'),
	(6, 'Manajer Satuan Pengawas Intern', 'Deleted', 'system'),
	(6, 'Manajer Cabang Purwokerto 1', 'Enabled', 'system'),
	(6, 'Manajer Perlengkapan', 'Enabled', 'system'),
	(6, 'Manajer Unit Bisnis AMDK', 'Enabled', 'system'),
	(12, 'Admininstrasi', 'Enabled', 'system'),
	(12, 'Programmer', 'Enabled', 'system'),
	(12, 'Technical Support', 'Enabled', 'system'),
	(12, 'Kasir', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Teknik Cabang (PTM)', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Teknik Cabang (PMS)', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Teknik Cabang (PJ)', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Teknik Cabang (Adm RAB)', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Teknik Cabang (Adm Kegiatan Teknik)', 'Enabled', 'system'),
	(6, 'Manajer SPI', 'Enabled', 'system'),
	(6, 'Manajer Produksi & Distribusi 2', 'Enabled', 'system'),
	(6, 'Manajer Bagian Pengendalian Teknik', 'Enabled', 'system'),
	(6, 'Manajer Cabang Purwokerto 2', 'Enabled', 'system'),
	(6, 'Manajer Cabang Ajibarang', 'Enabled', 'system'),
	(6, 'Manajer Cabang Wangon', 'Enabled', 'system'),
	(9, 'Supervisor Satuan Pengawas Intern', 'system'),
	(9, 'Supervisor Bagian Perencanaan & Pengembangan', 'Enabled', 'system'),
	(9, 'Supervisor Bagian Produksi & Distribusi 1', 'Enabled', 'system'),
	(9, 'Supervisor Bagian Produksi & Distribusi 2', 'Enabled', 'system'),
	(9, 'Supervisor Bagian Pengendalian Teknik', 'Enabled', 'system'),
	(9, 'Supervisor Bagian Kesekretariatan', 'Enabled', 'system'),
	(9, 'Supervisor Bagian Sumber Daya Manusia & TI', 'Enabled', 'system'),
	(9, 'Supervisor Bagian Perlengkapan', 'Enabled', 'system'),
	(9, 'Supervisor Bagian Adm. & Keuangan Cabang', 'Enabled', 'system'),
	(9, 'Supervisor Bagian Pelayanan Cabang', 'Enabled', 'system'),
	(9, 'Supervisor Bagian Teknik Cabang', 'Enabled', 'system'),
	(9, 'Supervisor Unit Bisnis AMDK', 'Enabled', 'system'),
	(9, 'Supervisor Bagian Keuangan', 'Enabled', 'system'),
	(12, 'Staff Satuan Pengawas Intern', 'Enabled', 'system'),
	(12, 'Staf Bagian Perencanaan & Pengembangan', 'Enabled', 'system'),
	(12, 'Staf Bagian Produksi & Distribusi (administrasi)', 'Enabled', 'system'),
	(12, 'Staff Sub Bag Pengendalian Distribusi (teknik)', 'Enabled', 'system'),
	(12, 'Staf Bagian Produksi & Distribusi dengan tugas pengendalian produksi pada mata air dan pompa', 'Enabled', 'system'),
	(12, 'Staf Bagian Produksi & Distribusi dengan tugas di unit IPA Gunung Tugel', 'Enabled', 'system'),
	(12, 'Staf Bagian Produksi & Distribusi dengan tugas di unit IPA Sidabowa, IPA Kemranjen, IPA Kejawar dan IPA Kaliori', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Penjaminan Mutu Air', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Mekanikal & Elektrikal', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Pengendalian Kehilangan Air', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Mekanikal & Elektrikal (Admin)', 'Enabled', 'system'),
	(12, 'Staff Sub Bag pada Bagian Kesekretariatan', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Akuntansi', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Anggaran & Pelaporan', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Perbendaharaan', 'Enabled', 'system'),
	(12, 'Staf Bagian Sumber Daya Manusia & TI', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Teknologi Informasi (administrasi)', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Teknologi Informasi (programmer)', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Teknologi Informasi (Performa Server, Hardware, jaringan & Mikrotik)', 'Enabled', 'system'),
	(12, 'Staf Sub Bag pada Bagian Perlengkapan', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Adm. & Keuangan Cabang', 'Enabled', 'system'),
	(12, 'Staf Sub Bag Pelayanan Cabang', 'Enabled', 'system'),
	(12, 'Staf Sub Bag AMDK (Admin)', 'Enabled', 'system'),
	(12, 'Staf Sub Bag AMDK', 'Enabled', 'system');

INSERT INTO `m_grade` (`level_id`, `grade`, `tukin`, `status`, `created_by`) VALUES
	(6, 1, 3000000, 'Enabled',  'system'),
	(6, 2, 3150000, 'Enabled',  'system'),
	(6, 3, 3300000, 'Enabled',  'system'),
	(9, 1, 1930500, 'Enabled',  'system'),
	(9, 2, 2216500, 'Enabled',  'system'),
	(9, 3, 2502500, 'Enabled',  'system'),
	(12, 1, 715000, 'Enabled',  'system'),
	(12, 2, 1072500, 'Enabled', 'system'),
	(12, 3, 1430000, 'Enabled', 'system'),
	(12, 4, 1787500, 'Enabled', 'system');